# Generated by Django 4.2.6 on 2023-10-18 02:05

from django.db import migrations, models
import enumfields.fields
import freshtrack.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('pantry_min', models.IntegerField()),
                ('pantry_max', models.IntegerField()),
                ('pantry_metric', enumfields.fields.EnumField(enum=freshtrack.enums.Metric, max_length=20)),
                ('pantry_tips', models.TextField()),
                ('pantry_after_opening_min', models.IntegerField()),
                ('pantry_after_opening_max', models.IntegerField()),
                ('pantry_after_opening_metric', enumfields.fields.EnumField(blank=True, enum=freshtrack.enums.Metric, max_length=20, null=True)),
                ('refrigerate_min', models.IntegerField()),
                ('refrigerate_max', models.IntegerField()),
                ('refrigerate_metric', enumfields.fields.EnumField(enum=freshtrack.enums.Metric, max_length=20)),
                ('refrigerate_tips', models.TextField()),
                ('refrigerate_after_opening_min', models.IntegerField()),
                ('refrigerate_after_opening_max', models.IntegerField()),
                ('refrigerate_after_opening_metric', enumfields.fields.EnumField(blank=True, enum=freshtrack.enums.Metric, max_length=20, null=True)),
                ('refrigerate_after_thawing_min', models.IntegerField()),
                ('refrigerate_after_thawing_max', models.IntegerField()),
                ('refrigerate_after_thawing_metric', enumfields.fields.EnumField(blank=True, enum=freshtrack.enums.Metric, max_length=20, null=True)),
                ('freeze_min', models.IntegerField()),
                ('freeze_max', models.IntegerField()),
                ('freezer_tips', models.TextField()),
                ('freezer_metric', enumfields.fields.EnumField(blank=True, enum=freshtrack.enums.Metric, max_length=20, null=True)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
